### ISSUE TITLE
Invalid argument... signature#sign#Refresh[19]..signature#sign#Place[28]

### ISSUE THREAD

**Issue by teto** [kshenoy/vim-signature#115]
I open a long file (660882 lines) and I have this error popping up continuously (doesn't seem to happen on other files).

Here is the mesage
```
Erreur détectée en traitant function signature#sign#Refresh[19]..signature#sign#Place[28]..<SNR>90_RefreshLine :                        
ligne   40 :                                                                                                                            
E474: Argument invalide 

```
using vim-signature 31028e7a0d015b04a51e721af155fd11d1b6ac76 with NVIM v0.1.5-154-g0bfc1f3

**Comment by kshenoy** [comment]
That's really weird if it errors out for only 1 particular file. Can you try deleting your shada file (or to start with move it somewhere else) so that nvim starts without any initial configuration and see if that helps?

This is the line it errors out on:

    execute 'sign place ' . l:id . ' line=' . a:lnum . ' name=Signature_' . l:str . ' buffer=' . bufnr('%')

Since you're able to work normally with other files, we can rule out the fact that the `execute` or the `sign place` commands have changed.

The only other thing that I can think of is that one of these must be invalid so can you please replace that line with the following:

    try
      execute 'sign place ' . l:id . ' line=' . a:lnum . ' name=Signature_' . l:str . ' buffer=' . bufnr('%')
    catch /E474/
      echo 'sign place ' . l:id . ' line=' . a:lnum . ' name=Signature_' . l:str . ' buffer=' . bufnr('%')
    endtry


and see what it dumps when it errors out? 

Thanks

**Comment by jkerian** [comment]
This is very similar to the error I was seeing in https://github.com/kshenoy/vim-signature/issues/121, so it might be fixed at the tip right now. I wouldn't think 660882 would be long enough to trigger that bug though.

If the tip doesn't fix the issue, would you please provide more debug information either by making the change kshenoy requested, or by typing

`:debug normal ma` somewhere in the file to get you into debug mode, followed by "step", and then keep hitting enter until the error shows up?

Copy the lines around the error (or the whole debug trace) and put it here.

**Comment by teto** [comment]
I think it's the same indeed, hence I close (I had to remove the file I had the problem with 'cos I was runing out of space :( )
