### ISSUE TITLE
How to enable colors?

### ISSUE THREAD

**Issue by trusktr** [kshenoy/vim-signature#136]
I only see dual tone:

![screen shot 2017-02-05 at 8 45 24 pm](https://cloud.githubusercontent.com/assets/297678/22634983/113fa4d4-ebe4-11e6-91d0-6a865bef29f6.png)

**Comment by kshenoy** [comment]
Can you paste the output of 

    :hi SignatureMarkText
    :hi Exception

**Comment by trusktr** [comment]
They are, respectively:

```
SignatureMarkerText xxx cleared
Exception      xxx links to Statement
```

**Comment by trusktr** [comment]
I'm running `:colorscheme hybrid` after the plugin wasset with `Plug 'kshenoy/vim-signature'`. Maybe that's why?

**Comment by kshenoy** [comment]
> I'm running `:colorscheme hybrid` after the plugin wasset with `Plug 'kshenoy/vim-signature'`.

I'm sorry but could you clarify what you mean by *wasset*? Is that a typo or the name of another plugin?

Also, can you point me to your vimrc?

**Comment by trusktr** [comment]
@kshenoy Hey, I means "was set" or "was installed" with vim-plug.

Here's my vimrc, where I define the `Plug`in: https://github.com/trusktr/.vimrc/blob/master/.vimrc#L470

Then later on down I set up my colors: https://github.com/trusktr/.vimrc/blob/master/.vimrc#L1152-L1181

But as I mentioned, I also tried disabling all colorscheme stuff, so that Vim uses its default colorscheme (only `:syntax enable`), but the result is the same, the bookmarks have no color.

**Comment by gpanders** [comment]
@trusktr Do you still have this issue? I am seeing the same thing

**Comment by kshenoy** [comment]
@trusktr @gpanders I'm very sorry for not checking my github in the past couple of months; I've been swamped at work. 

> Hey, I means "was set" or "was installed" with vim-plug.

Umm, yeah. It was a brainfart on my part : /

There was a bug in which the highlight groups would remain uninitialized if a colorscheme wasn't being explicitly loaded after Signature. This fix should address that. This can be tested with the following vim setup:
````
/home/kshenoy/.vim
`-- pack
    `-- bundles
        `-- start
            `-- vim-signature
````

and having nothing else in the .vim directory

However, if you are loading the colorscheme and you're still seeing these highlight groups getting cleared then the issue is something else. It'd help me if you put `hi SignatureMarkText` right after loading Signature and checking its output while starting vim.

**Comment by gpanders** [comment]
> There was a bug in which the highlight groups would remain uninitialized if a colorscheme wasn't being explicitly loaded after Signature

Does this mean that I must load my colorscheme plugin after I load vim-signature? Or just that I need to call `:colorscheme <whatever>` after I install vim-signature?

I tried both, and unfortunately, the problem persists. I even tried using a completely fresh installation. I made the following `init.vim` file:

    call plug#begin('signature_test')
    Plug 'kshenoy/vim-signature'
    call plug#end()

and started with `nvim -u init.vim`. I tried with both vanilla Vim and Neovim with the same result.

For what it's worth, I'm using the Solarized colorscheme with a light background in Tmux.

**Comment by kshenoy** [comment]
> Does this mean that I must load my colorscheme plugin after I load vim-signature? Or just that I need to call :colorscheme <whatever> after I install vim-signature?

You can call `:colorscheme` wherever you want. The order doesn't matter. The fix will help only in situations when `:colorscheme` isn't called at all and uses the default colorscheme. In other cases, it won't change anything and the behavior should be the same as earlier.

Hmm, I'm unable to reproduce it at my end. Can you just load vim-signature w/o a `:colorscheme` in your .vimrc and see if the highlight group SignatureMarkText is defined using `hi SignatureMarkText`? 

If it is, then load a colorscheme and repeat the same thing. If it says *cleared* after loading the colorscheme then add `autocmd Colorscheme * echo "Colorscheme was loaded"` to your .vimrc and do the same two steps as above.

Please paste the output for all 4.

**Comment by gpanders** [comment]
With the minimal vimrc I am seeing the marks be colored. So that does appear to be working. When I go back to my full vimrc, they are not. So I'm gonna keep digging into this.

When I open vanilla Vim with no other plugins installed except vim-signature, I keep getting the following error:

    Error detected while processing function signature#sign#Refresh[17]..signature#sign#GetMarkSignLine:
    line    6:
    E117: Unknown function: execute
This does not occur in Neovim.

**Comment by kshenoy** [comment]
@gpanders I found a bug in my code and fixed it. Can you give it a whirl?

**Comment by gpanders** [comment]
That did it! The marks are now colored. Thanks for looking into this.

**Comment by kshenoy** [comment]
Np, glad it worked. @trusktr Sorry for the delay
