### ISSUE TITLE
Special characters for markers?

### ISSUE THREAD

**Issue by dbmrq** [kshenoy/vim-signature#164]
I just added this to my .vimrc:

```vim
let g:SignatureIncludeMarkers = '▶︎!@#$%ˆ&*('
```

Hoping `m0` would give me that little arrow as a marker. But the markers just completely stopped working instead. Is there a reason why some characters aren't allowed as markers?

Thanks!

**Comment by kshenoy** [comment]
I was able to manually place a sign with the arrow so it's definitely possible. I'll look into this over the weekend

**Comment by dbmrq** [comment]
Awesome, thanks!

**Comment by gkapfham** [comment]
Thanks for suggesting this feature @dbmrq and agreeing to look into it @kshenoy. I too would really appreciate the ability to use special characters as markers! Please let me know once the feature is implemented so that I can try it out and report back on whether or not it works correctly in Vim 8 and Neovim 0.3.1-dev.

**Comment by kshenoy** [comment]
I looked into this and the code that messes things up is the following in autoload/signature/utils.vim::signature#utils#Input()

    if match(l:in, '\d') >= 0
      let l:char = strpart(b:SignatureIncludeMarkers, l:in, 1)

The help for `strpart` says that it counts bytes and not characters. For simple characters this wasn't an issue since they are single-byte wide while the arrow is two bytes wide. Thus something like `echo strpart('▶︎!@#$%ˆ&*(', 0, 1)` wouldn't work correctly.

It also recommends using `strcharpart` to count the no. of characters and `echo strcharpart('▶︎!@#$%ˆ&*(', 0, 1)` correctly displays the arrow. However, I tried using `echo strcharpart('▶︎!@#$%ˆ&*(', 1, 1)` to get the exclamation mark and it didn't work. It seems I have to skip one character since the arrow is a double-wide character and use `echo strcharpart('▶︎!@#$%ˆ&*(', 2, 1)` to be able to do that.

I'm trying to figure out how to recognize that something is double-wide in order to increment the index by 1 or if there's a better way of going about it.

**Comment by dbmrq** [comment]
That's really weird that `strcharpart('▶︎!@#$%ˆ&*(', 0, 1)` won't get the exclamation mark.

However, this seems to work:

```vim
function! GetChar(string, position)
    let string = a:string
    let i = 0
    while i < strchars(a:string, 1)
        if i == a:position
            return strcharpart(string, 0, 1)
        else
            let string = substitute(string, '.', '', '')
        endif
        let i += 1
    endwhile
endfunction
```

**Comment by dbmrq** [comment]
Oh, and since the regex pattern seems to work properly, the function can be further simplified to this:

```vim
function! GetChar(string, pos)
    let pattern = '.\{-' . a:pos . '}\(.\).*'
    return substitute(a:string, pattern, '\1', '')
endfunction
```

So your code could be changed to this:

```vim
if match(l:in, '\d') >= 0
    let pattern = '.\{-' . l:in . '}\(.\).*'
    let l:char = substitute(b:SignatureIncludeMarkers, pattern, '\1', '')
    " ...
```

(I didn't test it, but it should work.)

**Comment by gkapfham** [comment]
Hello @kshenoy and @dbmrq! I know that this issue is already closed, but I wanted to report that I have been using the improved version of this plugin for several days with `NVIM v0.3.1-dev` on Ubuntu 16.04 and I have not had any problems with the new functionality. I have been using a `g:SignatureIncludeMarkers` similar to the one suggested by @dbmrq while placing the markers in a wide variety of different locations in the files that I am editing. So far, I have not noticed any problems. Thanks for improving the plugin, I really enjoy using it on a regular basis!

**Comment by dbmrq** [comment]
@gkapfham No problem, thanks for letting us know. :)
