### ISSUE TITLE
:SignatureListMarkers '!',3 very strange

### ISSUE THREAD

**Issue by yueyihui** [kshenoy/vim-signature#167]
:SignatureListMarkers '!',3 there is a long strip which is marked onto the first item, why not let it mark onto the one which is '!'

**Comment by kshenoy** [comment]
Hello, sorry for the late response. I've been a bit preoccupied with work.

Can you give an example of what the issue is and, if possible, a screenshot?

This is a sample text with two markers placed on lines 1 and 8:

![cap1](https://user-images.githubusercontent.com/1559554/44059815-d3d3059c-9f0f-11e8-8936-b284bfce4418.png)

and when I run `:SignatureListMarkers '!', 3`, it shows lines 1 and 8 with 3 lines of context around them:
![cap3](https://user-images.githubusercontent.com/1559554/44059853-ebd36ace-9f0f-11e8-990d-83361a1bbc28.png)

It seems to be behaving correctly.

**Comment by yueyihui** [comment]
it is not a bug report, is a proposal is that when show up the plist the highlight look like very strange, because it was at the first, the proposal is that move highlight to the Signature, the screenshot after my change as below, the default hightlight at the first Signature
![image](https://user-images.githubusercontent.com/16845961/44502220-1242c780-a6c3-11e8-9d7c-7a003c93e8b6.png)
