### ISSUE TITLE
Question: marks vs markers?

### ISSUE THREAD

**Issue by alexeRadu** [kshenoy/vim-signature#176]
Hey, This is not an issue but more of a question regarding the design. What is the difference between markers and marks. I know that markers come from numbers (converted to their shift value) and mars are letters but other than that?
And also there is a limited number of marks + markers available. Why not assign a number to them and keep a list internally. And also make all of them global (or project base)? I think this would have resulted in a simpler design.

**Comment by kshenoy** [comment]
Marks are a feature built into vim - lowercase marks are local to the buffer while the uppercase are global and shared across all buffers/files. Thus most decisions regarding marks are dictated by vim's design decisions and not mine. The only thing I added to it was displaying it on the side.

I felt marks were a tad limited in what they could do and wanted to fill in a few holes - one thing in particular was I wanted to group a few of them together and have multiple such groups. Marks are not really suitable for this as they're specific to the line they're used on and as such you can have only 1 type of a mark in a given file. That's where markers come in - you can place multiple markers of the same type and jump between markers of the same/different types. I think that's about the biggest difference between the two.

> And also there is a limited number of marks + markers available.

As I mentioned above, the no. of marks available are dictated by how vim implements them and I have no control over it. Similarly, markers were originally meant to expand upon marks and thus were heavily influenced by them. You can see this in how markers are placed/removed, it's very similar to marks i.e. it uses only a single character. Furthermore, 
there is the issue of using and representing them - all alphabetical characters were used by marks, special character marks have a specific meaning and are already defined by vim so that left just numeric characters - hence there are only 10 markers by default - 1 symbol per digit. At the end of the day, the way I was intending to use them (in groups), a handful felt sufficient and I didn't push further.

> Why not assign a number to them and keep a list internally. And also make all of them global (or project base)? I think this would have resulted in a simpler design.

What you're describing sounds like a way to generically implement bookmarks and if that was the intention here then I'd agree with your statement. However, I don't think of marks and/or markers as true bookmarks; the global marks come close to approximating them but they still fall short in many areas and IMO default vim doesn't support true bookmarking. 

Having said that, I do use a number to represent each marker (it's a function of the buffer no. and line no.) and store it in a list. The representation of the marker is decoupled from the storage and I think theoretically there really is no limit to how many markers can be defined. The limits are dictated more by the mechanism of placing/removing them as described above.

Hope this answers all your questions.
