### ISSUE TITLE
Conflicts with NERDTree menu ('m' key)

### ISSUE THREAD

**Issue by techniq** [kshenoy/vim-signature#3]
When vim-signature is installed, I am unable to toggled NERDTree's menu (m key). I tried setting g:SignatureDefaultMappings = 0, but that didn't work.

**Comment by chenhouwu** [comment]
Here to reproduce the problem I met:
1. I open a new file `a.txt`, then I have the `m.` keymap.
2. I open the *nerdtree*, and then navigate back to the `a.txt` window, then the `m.` keymap is still there.
3. I run `:e b.txt`, the `m.` keymap is gone. I run `:e a.txt`, the `m.` keymap is still absent. I open a file `c.txt` from *nerdtree*, the `m.` keymap is missing too.
3. I navigate to the *nerdtree* window, and then navigate back to `a.txt` window without opening a new buffer, then the `m.` keymap is back again.

**Comment by kshenoy** [comment]
@chenhouwu Hi, I'm able to reproduce this at my end too. Looks like when you press `<CR>` on a file in NerdTree, it doesn't trigger the `BufLeave` event. 

That is what I use to recreate maps for Signature upon leaving the NerdTree buffer. And the only reason to create and remove maps is because of the conflicting `m` map in NERDTree. Would you be amenable to using `M` in NerdTree instead of `m`?

If yes, add the following to your .vimrc:

    let g:NERDTreeMapMenu='M'

and delete the following lines from vim-signature/plugin/signature.vim:

    " To avoid conflicts with NERDTree. Figure out a cleaner way.
    " Food for thought: If NERDTree creates buffer specific maps, shouldn't it override Signature's maps?
    autocmd BufEnter,FileType * if (  (&filetype ==? 'nerdtree')
                             \     || (&filetype ==? 'netrw')
                             \     )
                             \|   call signature#utils#Maps('remove')
                             \| endif
    autocmd BufLeave * if (  (&filetype ==? 'nerdtree')
                    \     || (&filetype ==? 'netrw')
                    \     )
                    \|   call signature#utils#Maps('create')
                    \| endif

This should at least help you avoid this issue.

**Comment by chenhouwu** [comment]
I like this solution.  Simple and effective.

But modify the source code is not optimal, because I want to keep up with the latest codes, and local modification will prevent it if without additional care.

Is it possible to **delete them in the official repository** and describe this solution on the README?

**Comment by chenhouwu** [comment]
another solution is even simpler:

1. for bufenter, if is in nerdtree, then remove maps.
if not in nerdtree, and key is not mapped(is there such a flag already?), then create the map.
2. no need to response to the bufleave event.

**Comment by chenhouwu** [comment]
I just test the `bufleave` event, and found:

1. if the buffer is active buffer is `a.txt`, and you press <CR> on the `a.txt` item of `nerdtree`, then `bufleave` event is not fired. the `bufenter` for `a.txt` is also not fired.
2. if the buffer is active buffer is `a.txt`, and you press <CR> on the `b.txt` item of `nerdtree`. then both event is fired as expected.

**Comment by kshenoy** [comment]
> Is it possible to delete them in the official repository and describe this solution on the README?

I'd like to think about it a little more before I go down this route. 

Thanks for expanding and describing the two cases. I was wondering why this wasn't seen earlier. I guess it's pretty rare that someone would do something like you described in case 1 i.e. open NERDTree and jump back to the same buffer using NERDTree itself. It sounds like a bug in NERDTree since any behavior that depends on BufLeave will not get triggered. Please report it there; they might be interested in knowing about it.

**Comment by kshenoy** [comment]
Hey, I read your [this reply](https://github.com/kshenoy/vim-signature/issues/3#issuecomment-222589998) and wanted to make sure that I understood you correctly. Are you seeing both `enter nerdtree` and `leave nerdtree` messages being echoed or are you able to see only `enter nerdtree` but not `leave nerdtree` when you re-enter the same buffer?

**Comment by chenhouwu** [comment]
@kshenoy I furtherly traced the event in a more verbose way, and updated [this comment](https://github.com/kshenoy/vim-signature/issues/3#issuecomment-222589998)

**Comment by kshenoy** [comment]
Hi @chenhouwu I deleted that code in trunk since I haven't heard back from NERDTree yet.
