### ISSUE TITLE
How to show signature and line number in same column？

### ISSUE THREAD

**Issue by chpz** [kshenoy/vim-signature#83]

**Comment by kshenoy** [comment]
If a line has a mark, do you want to see the mark instead of the line number?

**Comment by chpz** [comment]
Yes

**Comment by kshenoy** [comment]
Well, by default vim puts line numbers and signs in separate columns. So doing what you want isn't possible.

However, if you're willing to settle for relative line numbering, then you can try installing https://github.com/vim-scripts/RltvNmbr.vim This plugin will show relative line numbers as signs and by disabling vim's numbering, you could get close to what you want. 

However, I don't think it's going to work very well since Signature and RltvNmbr.vim are going to clobber each other by trying to place signs on the same line.
