### ISSUE TITLE
Remapping `m`

### ISSUE THREAD

**Issue by e-dorigatti** [kshenoy/vim-signature#87]
Hello,
for some reason I am not able to make the following remap work: `nnoremap <Leader>m m.`.  Actually, I cannot make any remap involving `m + <command>`, for example `nnoremal <C-L> ma`. My leader is the space key, and I did not remap `:` (I remapped `,` to `:` though)

**Comment by kshenoy** [comment]
I'm not sure I understand the issue. 

1. Do you have the default mappings for Signature and is that when you're facing this issue?
2. Where are you trying to do `nnoremap <Leader>m m.`

**Comment by e-dorigatti** [comment]
Yes, I have the default mappings. I am trying to put that into my .vimrc
but it doesn't even work from inside vim

**Comment by kshenoy** [comment]
Hey, sorry, I've been really busy at work lately and it's only going to get worse with projects coming to a close :(

I'll try to work on this but can't promise it'll be any time soon.

**Comment by e-dorigatti** [comment]
No worries, be strong and good luck! Thanks for your work ;)

**Comment by kshenoy** [comment]
Doh! I missed the obvious bit here. 'm' is already mapped to `:<C-U>call signature#Input()<CR>`
That's why if you use `nnoremap <C-L> ma`, you trigger only the default behavior of 'm' and not the new one.

Check this [Stack Overflow reply](http://stackoverflow.com/a/3776182/734153) for details.

You can make the maps by simply using `nmap` instead of `nnoremap`

    nmap <Leader>m m.
    nmap <C-L> ma

Hope this helps

**Comment by e-dorigatti** [comment]
It works, thank you!
