### ISSUE TITLE
Marking visually selected areas?

### ISSUE THREAD

**Issue by iago-lito** [kshenoy/vim-signature#94]
Hey guys. We kinda like the idea of signature, and we are working on a small plugin for saving and restoring another kind of marks: marks to save and restore visually selected areas. It is young and small, but consistent so far and it is starting to get snappy, check it out [there](https://github.com/iago-lito/vim-visualMarks).

Wouldn't it be nifty to integrate it into signature, displaying colored marks locating the start / slash / the end of a selection, navigating across them etc.?

Should you be interested, please drop us a line and we'd be happy to push to your repo' :)

**Comment by kshenoy** [comment]
Hello @iago-lito, I'm subscribe to the unix philosophy of creating one tool for one job and ensuring that it does the job well. So much so that I considered splitting markers away from marks but didn't do so only because of a large portion of code being common to both.

Thus, I'm not in favor of merging two different tools offering completely different features. However, if you do anything from my side like making available some functions etc. do let me know and I'll see what I can do.
